[project]
name = "youtube-mcp-server"
version = "0.1.0"
description = "MCP server for fetching YouTube video transcripts"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "mcp[cli]>=1.8.1",
    "click<8.2.0",
]
